default:
  image: node:20
  tags:
    - catanica-local
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - .npm/
  before_script:
    - npm ci --cache .npm --prefer-offline

stages:
  - test
  - deploy

test:
  stage: test
  script:
    - npm run test
    - npm run build

pages:
  stage: deploy
  script:
    - npm run build
  pages:
    publish: dist
  artifacts:
    paths:
      - dist
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
